version: '3.5'

networks:
  dev:
    driver: bridge

services:
  virtualpetcare-postgres:
    container_name: virtualpetcare-postgres-containerTwo
    image: postgres:latest
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: groot
      POSTGRES_DB: VirtualPetCareDb
    networks:
      - dev
    restart: unless-stopped

  virtualpetcare-pgadmin:
    container_name: virtualpetcare-container-pgadminTwo
    image: dpage/pgadmin4:latest
    depends_on:
      - virtualpetcare-postgres
    ports:
      - "6060:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: groot
    networks:
      - dev
    restart: unless-stopped

  virtualpetcare-apiservice:
    container_name: virtualpetcare-container-apiserviceTwo
    image: veyseldilim/virtualpetcareapiservice:latest
    build:
      context: .
      dockerfile: Dockerfile # You may need to adjust this if your Dockerfile is in a different location
    ports:
      - "7255:7255" # HTTPS
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:7255"
      
      SecretThree: "MyVerySecretActualSecretKeyIsThisSecretKeyNothingMore" # Replace with your actual secret key
    networks:
      - dev
    depends_on:
      - virtualpetcare-postgres
    restart: unless-stopped